output "region" {
  value = var.region 
}
output "eks_cluster_name" {
  value = aws_eks_cluster.aws_eks.name 
}
output "eks_cluster_endpoint" {
  value = aws_eks_cluster.aws_eks.endpoint
}

output "eks_cluster_certificate_authority" {
  value = aws_eks_cluster.aws_eks.certificate_authority 
}

output "db_id" {
  value       = aws_db_instance.postgresql.id
  description = "The database instance ID"
}

output "db_name" {
  value       = aws_db_instance.postgresql.name
  description = "The database name"
}

output "db_username" {
  value       = aws_db_instance.postgresql.username
  description = "The database port"
}

output "db_security_group_id" {
  value       = aws_security_group.db_security_group.id
  description = "Security group ID of the database"
}

output "db_hosted_zone_id" {
  value       = aws_db_instance.postgresql.hosted_zone_id
  description = "The zone ID for the autogenerated DNS name given in endpoint"
}

output "db_hostname" {
  value       = aws_db_instance.postgresql.address
  description = "Public DNS name of database instance"
}

output "db_port" {
  value       = aws_db_instance.postgresql.port
  description = "Port of database instance"
}

output "db_endpoint" {
  value       = aws_db_instance.postgresql.endpoint
  description = "Public DNS name and port separated by a colon"
}
